pipeline:
  projectIdentifier: auto_stopping_lab
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: creds
        identifier: creds
        template:
          templateRef: account.generate_and_save_aws_keys
          versionLabel: "1"
          gitBranch: main
    - stage:
        name: apply
        identifier: apply
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: <+input>
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: Run
                  spec:
                    connectorRef: account.harnessImage
                    image: ghcr.io/terraform-linters/tflint
                    shell: Sh
                    command: tflint
                  name: tflint
                  identifier: tflint
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - parallel:
                  - step:
                      type: Run
                      spec:
                        connectorRef: account.harnessImage
                        image: bridgecrew/checkov
                        shell: Sh
                        command: checkov -f <+execution.steps.plan.output.outputVariables.plan>
                      name: checkov
                      identifier: checkov
                  - step:
                      type: Run
                      spec:
                        connectorRef: account.harnessImage
                        image: aquasec/tfsec
                        shell: Sh
                        command: tfsec --soft-fail .
                      name: tfsec
                      identifier: tfsec
              - step:
                  type: IACMApproval
                  name: approve
                  identifier: approve
                  spec:
                    autoApprove: true
                  timeout: 1h
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 10m
                  spec:
                    command: apply
            "":
              type: Run
              spec:
                connectorRef: account.harnessImage
                image: bridgecrew/checkov
                shell: Sh
                command: checkov -f <+execution.steps.plan.output.outputVariables.plan>
              name: checkov
              identifier: checkov
        tags: {}
  identifier: iacm_ccm_demo
  name: iacm ccm demo
